### ISSUE TITLE
BundleAccessors.class is a duplicate but no duplicate handling strategy has been set

### ISSUE THREAD

**Issue by heruan** [radoslaw-panuszewski/typesafe-conventions-gradle-plugin#19]
When using the plugin I'm getting this exception that seems related to the version bundles:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':build-logic:jar'.
> Entry org/gradle/accessors/dm/LibrariesForSpring$BundleAccessors.class is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.12.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

This my project structure:

```
.
├── build-logic
│   ├── build
│   ├── build.gradle.kts
│   ├── settings.gradle.kts
│   └── src
│    └── main
│        └── kotlin
│            ├── java-application-conventions.gradle.kts
│            ├── java-common-conventions.gradle.kts
│            ├── java-library-conventions.gradle.kts
│            ├── java-native-image-conventions.gradle.kts
│            ├── java-spring-boot-conventions.gradle.kts
│            └── java-vaadin-conventions.gradle.kts
├── foo-module
│   ├── build.gradle.kts
│   └── src
├── bar-module
│   ├── build.gradle.kts
│   └── src
├── gradle
│   ├── libs.versions.toml
│   ├── spring.versions.toml
│   └── vaadin.versions.toml
├── build.gradle.kts
├── gradle.properties
└── settings.gradle.kts
```

This my my `build-logic/settings.gradle.kts`:

```kotlin
rootProject.name = "build-logic"
plugins {
    id("dev.panuszewski.typesafe-conventions") version "0.4.1"
}
```

This is the root `settings.gradle.kts`:

```kotlin
dependencyResolutionManagement {
    versionCatalogs {
        create("spring") {
            from(files(rootProject.projectDir.resolve("./gradle/spring.versions.toml")))
        }
        create("vaadin") {
            from(files(rootProject.projectDir.resolve("./gradle/vaadin.versions.toml")))
        }
    }
}
pluginManagement {
    includeBuild("build-logic")
}
include("foo-module", "bar-module")
```

And this is the `spring.versions.toml`:

```toml
[versions]
boot = "3.4.2"

[libraries]
boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "boot" }
boot-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "boot" }
boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

[plugins]
boot = { id = "org.springframework.boot", version.ref = "boot" }
```
